apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: job-finder
data:
  default.conf: 
    server {
    listen 80;
    server_name localhost;

    location /staticfiles/ {
      alias /efs/staticfiles/;
    }

    location / {
      proxy_pass http://django-service:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
