apiVersion: batch/v1
kind: Job
metadata:
  name: django-collectstatic
  namespace: job-finder
spec:
  template:
    metadata:
      labels:
        app: django-collectstatic
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: collectstatic
        image: ghcr.io/themdq/jobsearch:latest
        command: ["python", "manage.py", "collectstatic", "--noinput"]
        
        # Переменные окружения
        envFrom:
        - configMapRef:
            name: app-env
        
        # Переменные окружения из Secrets
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_SECRET_KEY
        - name: DATABASE_HOST
          value: "postgres"
  
  backoffLimit: 3  # Повторить 3 раза при ошибке