apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  labels:
    type: local
    app: django-staticfiles
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath: 
    path: "/efs/staticfiles"