apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: job-finder
  labels:
    app: django
spec:
  type: ClusterIP  # Или NodePort для прямого доступа
  selector:
    app: django
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None

---
# Опционально: NodePort для прямого доступа с хоста
apiVersion: v1
kind: Service
metadata:
  name: django-nodeport
  namespace: job-finder
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30800  # Доступ по <IP-сервера>:30800
    protocol: TCP